config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # get 'tops/index'
  root to: 'tops#index'
  resources :tops, only: [:show]
  resources :goals, only: [:create, :update]
  resources :incomes, only: [:new, :create, :edit, :update, :destroy]
  resources :outgos, only: [:new, :create, :edit, :update, :destroy]
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    # ユーザー登録していないと表示されない
    if current_user.present?
      # 目標の表示
      user = User.find(current_user.id)
      @goal = user.goal
      # 目標の表示ここまで

      # 貯金合計金額の表示
      user = User.find(current_user.id)
      income_sum = user.incomes.sum(:price)
      outgo_sum = user.outgos.sum(:price)
      @total = income_sum - outgo_sum
      # 貯金合計金額の表示ここまで
    end
  end

  def show
    # user = User.find(params[:id])
    user = User.find(current_user.id)
    @incomes = user.incomes.order(date: :desc)
    @outgos = user.outgos.order(date: :desc)
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<%# ヘッダー %>
<%= render 'shared/header' %>
<%# ヘッダーここまで %>
<div class="notice2" id="notice2">
  <%= flash[:notice2] %>
</div>
<div class="main">
  <div class="goal-contents">
    <p class="goal-title">目標(もくひょう)</p>
    <div class="goal-text">
      <% if current_user.present? && @goal.present? %>
        <div id="data-id" data_id=<%= @goal.id %>></div>
      <% end %>
      <%= flash[:alert] %>
      <%= form_with model: @goal, url: goals_path, class:"goal-form", id:"remove", local: true do |f| %>
        <%#= render "users/shared/error_messages", resource: f.object %>
        <%= f.text_area :text, placeholder: '目標(もくひょう)を入力してね！(25文字まで)', class:"input-box", maxlength:"25" %>
        <%= f.submit "決定(けってい)", id:"btn-label", class:"btn-hidden" %>
      <% end %>
    </div>
  </div>
  <%# if current_user.present? && @goal.present? %>
    <%#= @goal.text %>
  <%# end %>
  
  <div class="menu-contents">
    <div class="saving">
      <p class="saving-title">たまったお金</p>
      <p class="saving-total"><%= @total %>円</p>
    </div>
    <% unless user_signed_in? %>
      <div class="saving">
        <p class="saving-title">たまったお金</p>
        <p class="saving-total"><%= @total %>---円</p>
      </div>
    <% end %>
    <div class="circle-box">
      <div class="item">
        <%= link_to new_income_path, class:"menu-img-content" do %>
          <%= image_tag("cat-1.png", class:"menu-icon") %>
          <p>ためる</p>
        <% end %>
      </div>
      <div class="item">
        <%= link_to new_outgo_path, class:"menu-img-content" do %>
          <%= image_tag("cat-2.png", class:"menu-icon") %>
          <p>ひきだす</p>
        <% end %>
      </div>
      <div class="item">
        <% if current_user.present? %>
          <%= link_to top_path(current_user.id), class:"menu-img-content" do %>
            <%= image_tag("cats-1.png", class:"menu-icon3") %>
            <p>履歴(りれき)</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tops/show.html.erb
<%= render 'shared/header' %>

<%# 切り替えボタン %>
<div class="switch">
  <button id="income-btn">
    <h1>たまったお金</h1>
  </button>
  <button id="outgo-btn">
    <h1>つかったお金</h1>
  </button>
</div>
<%# 切り替えボタンここまで %>

<%# 収入の履歴 %>
<div id="income-hidden">
  <%= month_calendar events: @incomes do |date, incomes| %>
    <%= date.day %>
    <% sum = 0 %>
    <% incomes.each do |income| %>
      <% sum += income.price%>
    <% end %>
    <% if sum != 0 %>
      <div class="budget-box">
        <div class="budget-font">
          <span id="income"><%= sum %>円</span>
        </div>
      </div>
    <% end %>
  <% end %>

  <h1 class="history-title">これまでの記ろく</h1>
  <div class='flash-message'>
    <%= flash[:alert] %>
  </div>
  <ul class='event-contents'>
    <div class="event-title">
      <li><span>日付(ひづけ)</span></li>
      <li><span>メモ</span></li>
      <li><span>金額(きんがく)</span></li>
      <li><span>設定(せってい)</span></li>
    </div>
    <div class="event-content", id="event-index">
      <% @incomes.each do |income| %>
        <li> 
          <div class='date-content'>
            <%= income.date.strftime("%Y年%m月%d日") %>
          </div>
          <div class='description-content'>
            <%= income.description %>
          </div>
          <div class='price-content'>
            <span><%= income.price %>円</span>
          </div>
          <div id="edit-delete">
            <div id="edit-delete-content">
            <%# <div id="edit-btn-contet"> %>
              <%= link_to '変更(へんこう)', edit_income_path(income.id), class:"edit-btn" %>
            <%# </div> %>
            <%# <div id="delete-btn-contet"> %>
              <%= link_to '削除(さくじょ)', income_path(income.id), method: :delete, class:"delete-btn" %>
            <%# </div> %>
            </div>
          </div>
        </li>
      <% end %>
    <div>
  </ul>
</div>
<%# 収入の履歴ここまで %>

<%#= month_calendar events: @all do |date, all| %>
<%#= date.day %>
<%# all.each do |i| %>
  <%# <div> %>
    <%#= i.price %>
  <%# </div> %>
<%# end %>
<%# end %>


<%# 支出の履歴 %>
<div id="outgo-hidden">
  <%= month_calendar events: @outgos do |date, outgos| %>
    <%= date.day %>
    <% sum = 0 %>
    <% outgos.each do |outgo| %>
      <% sum += outgo.price%>
    <% end %>
    <% if sum != 0 %>
      <div class="budget-box">
        <div class="budget-font">
          <span id="outgo"><%= sum %>円</span>
        </div>
      </div>
    <% end %>
  <% end %>

  <h1 class="history-title">これまでの記ろく</h1>
  <ul class='event-contents'>
    <div class="event-title">
      <li><span>日付(ひづけ)</span></li>
      <li><span>メモ</span></li>
      <li><span>金額(きんがく)</span></li>
      <li><span>設定(せってい)</span></li>
    </div>
    <div class="event-content">
      <% @outgos.each do |outgo| %>
        <li> 
          <div class='date-content'>
            <%= outgo.date.strftime("%Y年%m月%d日") %>
          </div>
          <div class='description-content'>
            <%= outgo.description %>
          </div>
          <div class='price-content'>
            <span><%= outgo.price %>円</span>
          </div>
          <div id="edit-delete">
            <div id="edit-delete-content">
              <%= link_to '変更(へんこう)', edit_outgo_path(outgo.id), class:"edit-btn" %>
              <%= link_to '削除(さくじょ)', outgo_path(outgo.id), method: :delete, class:"delete-btn" %>
            </div>
          </div>
        </li>
      <% end %>
    <div>
  </ul>
</div>
<%# 支出の履歴ここまで %>