config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # get 'tops/index'
  root to: 'tops#index'
  resources :tops, only: [:show]
  resources :goals, only: [:create, :update]
  resources :incomes, only: [:new, :create, :edit, :update, :destroy]
  resources :outgos, only: [:new, :create, :edit, :update, :destroy]
end

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class="top-page-contents">
    <%= link_to root_path, class:"top-img-content" do %>
      <%= image_tag("abstract-1751204_1280.png", class:"okodukai-icon") %>
      <h1 class="top-okodukai">おこづかいちょう</h1>
    <% end %>
    <div class="nav">
      <ul class="lists">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% else %>
          <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "login" %></li>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to 'アカウントを作る', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='top-page-header'>
  <%= link_to root_path, class:"top-img-content" do %>
    <%= image_tag("abstract-1751204_1280.png", class:"okodukai-icon") %>
    <h1 class="top-okodukai">おこづかいちょう</h1>
  <% end %>
</header>